server:
  port: 5000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:5002/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core-service
            - JwtAuthFilter
#        - id: cart-service
#          uri: http://localhost:8191/
#          predicates:
#            - Path=/cart/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-cart
#            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:5001/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-service
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
